// @generated automatically by Diesel CLI.

diesel::table! {
    /// Representation of the `groups` table.
    ///
    /// (Automatically generated by Diesel.)
    groups (id) {
        /// The `id` column of the `groups` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Integer,
        /// The `name` column of the `groups` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Text,
    }
}

diesel::table! {
    /// Representation of the `hosts` table.
    ///
    /// (Automatically generated by Diesel.)
    hosts (id) {
        /// The `id` column of the `hosts` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Integer,
        /// The `name` column of the `hosts` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Text,
        /// The `username` column of the `hosts` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        username -> Text,
        /// The `hostname` column of the `hosts` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        hostname -> Text,
        /// The `port` column of the `hosts` table.
        ///
        /// Its SQL type is `SmallInt`.
        ///
        /// (Automatically generated by Diesel.)
        port -> SmallInt,
    }
}

diesel::table! {
    /// Representation of the `keys` table.
    ///
    /// (Automatically generated by Diesel.)
    keys (id) {
        /// The `id` column of the `keys` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Integer,
        /// The `key_type` column of the `keys` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        key_type -> Text,
        /// The `key_base64` column of the `keys` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        key_base64 -> Text,
        /// The `comment` column of the `keys` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        comment -> Nullable<Text>,
        /// The `host_id` column of the `keys` table.
        ///
        /// Its SQL type is `Nullable<Integer>`.
        ///
        /// (Automatically generated by Diesel.)
        host_id -> Nullable<Integer>,
        /// The `user_id` column of the `keys` table.
        ///
        /// Its SQL type is `Nullable<Integer>`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Nullable<Integer>,
    }
}

diesel::table! {
    /// Representation of the `user_in_host` table.
    ///
    /// (Automatically generated by Diesel.)
    user_in_host (id) {
        /// The `id` column of the `user_in_host` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Integer,
        /// The `host_id` column of the `user_in_host` table.
        ///
        /// Its SQL type is `Nullable<Integer>`.
        ///
        /// (Automatically generated by Diesel.)
        host_id -> Nullable<Integer>,
        /// The `user_id` column of the `user_in_host` table.
        ///
        /// Its SQL type is `Nullable<Integer>`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Nullable<Integer>,
        /// The `options` column of the `user_in_host` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        options -> Nullable<Text>,
    }
}

diesel::table! {
    /// Representation of the `users` table.
    ///
    /// (Automatically generated by Diesel.)
    users (id) {
        /// The `id` column of the `users` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Integer,
        /// The `username` column of the `users` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        username -> Text,
        /// The `enabled` column of the `users` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        enabled -> Bool,
    }
}

diesel::joinable!(keys -> hosts (host_id));
diesel::joinable!(keys -> users (user_id));
diesel::joinable!(user_in_host -> hosts (host_id));
diesel::joinable!(user_in_host -> users (user_id));

diesel::allow_tables_to_appear_in_same_query!(
    groups,
    hosts,
    keys,
    user_in_host,
    users,
);
